### ISSUE TITLE
Indentation error thrown if comment is incorrectly indented

### ISSUE THREAD

**Issue by karl-malakoff** [PyCQA/pydocstyle#477] opened 2020-05-13 23:28 UTC
I've found an odd bug where an indentation error is thrown by the ast module if certain conditions are met.

The following minimal example will throw the error below.

```python
class example:

    def func(self, arg:str): 
        """
        description

        Arguments:
            arg (str): I'm an arg
        """

#  the quick fox jumps over the lazy dog
        
        pass
```

```Traceback (most recent call last):
  File "/home/support/miniconda3/envs/peat_test/bin/pydocstyle", line 8, in <module>
    sys.exit(main())
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/cli.py", line 68, in main
    sys.exit(run_pydocstyle())
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/cli.py", line 45, in run_pydocstyle
    ignore_decorators=ignore_decorators))
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/checker.py", line 969, in check
    ignore_decorators):
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/checker.py", line 123, in check_source
    for error in errors:
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/checker.py", line 917, in check_docstring_sections
    yield from self._check_google_sections(lines, definition, docstring)
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/checker.py", line 903, in _check_google_sections
    yield from self._check_google_section(docstring, definition, ctx)
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/checker.py", line 796, in _check_google_section
    yield from cls._check_args_section(docstring, definition, context)
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/checker.py", line 748, in _check_args_section
    yield from ConventionChecker._check_missing_args(docstring_args, definition)
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/checker.py", line 762, in _check_missing_args
    function_args = get_function_args(definition.source)
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/site-packages/pydocstyle/checker.py", line 1002, in get_function_args
    function_arg_node = ast.parse(textwrap.dedent(function_string)).body[0].args
  File "/home/support/miniconda3/envs/peat_test/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    def func(self, arg:str): 
    ^
IndentationError: unexpected indent
```

I did some minimal debugging of the checker.py module and found that the string it passes to ast has a leading tab for the function func.

Removing any of the following resolves the error:
* the 'description' line in the doc comment
* Removing the 'Arguments:' line or changing it to anything else, eg 'Returns:'
* Removing the docstring entirely 
* Removing the pass statement at the bottom of the function

Fixing the indentation in the comment also fixes it as you would expect.

Even though this is bad style it is legal python so I would of expected this code to be passed though this module correctly if it was formatted like this.

**Comment by samj1912** [comment] 2020-05-14 06:55
Duplicate of https://github.com/PyCQA/pydocstyle/issues/437

**Closed by samj1912** 2020-05-14 06:55 UTC
