### ISSUE TITLE
Ignore missing docstring in main function of script

### ISSUE THREAD

**Issue by ajhynes7** [PyCQA/pydocstyle#532] opened 2021-04-18 19:15 UTC
Hello,

I have several Python scripts with this format:

```python
"""Description of the script."""


def main():
    # All of the script code.


if __name__ == "__main__":
    main()
    
```

It seems redundant to explain the script again inside the `main` function.

`pydocstyle` raises this error:

```
path/to/script.py:4 in public function `main`:
        D103: Missing docstring in public function
```

I don't want to ignore `D103` because it's useful for functions in other modules. 

I see that you have a `--match` option for selecting files that match a regular expression. Perhaps a feature could be added to ignore function names that match a regular expression?

Thanks.

**Comment by sigmavirus24** [comment] 2021-04-18 19:37
You can also use `# noqa` on the `def main():` line iirc to disable this

**Comment by ajhynes7** [comment] 2021-04-19 00:30
Ok thanks, that works as well. Do you think it would be useful though to add a command line option for excluding a function based on a regular expression? Something like `--match-function`.

If so, I can try contributing the feature.

**Comment by sigmavirus24** [comment] 2021-04-19 12:58
I don't but I'm not a maintainer

**Comment by samj1912** [comment] 2021-05-17 19:42
Related to/Duplicate of #537

**Closed by samj1912** 2021-05-17 19:42 UTC

**Comment by KaleabTessera** [comment] 2022-02-02 07:07
This feature would be appreciated! Adding `# noqa` to many files is not ideal.
