### ISSUE TITLE
6.2.1 Errors in doc verification of version

### ISSUE THREAD

**Issue by 597038837** [PyCQA/pydocstyle#617] opened 2023-01-03 10:14 UTC
`
def func(
    a: int,
    b: list,
    c: int = None,
    d: bool = False,
    e: bool = False,
) -> list:
    """Commit.

    commit.

    Args:
        a (int): commit.
        b (list): commit.
        c (int): commit.
        d (bool): commit.
        e (bool): commit.

    Results:
        [list]: []
    """
    return []
`

pydocstyle=6.2.1
`D417: Missing argument descriptions in the docstring (argument(s) b, c, d, e are missing descriptions in 'func' docstring)`

pydocstyle=6.1.0
`Pass`

**Comment by samj1912** [comment] 2023-01-03 10:19
Duplicate of #618

**Closed by samj1912** 2023-01-03 10:19 UTC
